# Makefile for 'set' module
#
# Imanol Avendano, CS50, 16X

# PROG =
OBJS = set.o
LIBS =

MAKE = make
CC = @gcc
CFLAGS = -Wall -pedantic -std=c11 -ggdb

# I have no tester program
# $(PROG): $(OBJS)
# 	$(CC) $(CFLAGS) $^ $(LIBS) -o $@

set.o: set.h

.PHONY: clean
	
clean:
	rm -f *~
	rm -f *.o